services:
  pico-build:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pico-build
    volumes:
      - ..:/home/builder/project
    working_dir: /home/builder/project
    tty: true
    stdin_open: true
    command: >
      bash -c "mkdir -p build && cd build && cmake .. && make -j$(nproc)"
